Models/AccountRegisterViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EtLiberLibrarium.Models
{
    public class AccountRegisterViewModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm Password")]
        [Compare("Password", ErrorMessage = "Password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }
}

Models/DatabaseBookViewModel.cs
using EtLiberLibrarium.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EtLiberLibrarium.Models
{
    public class DatabaseBookViewModel
    {
        public Book Book { get; set; }
    }
}

Models/DatabaseIndexViewModel.cs
using EtLiberLibrarium.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EtLiberLibrarium.Models
{
    public class DatabaseIndexViewModel
    {
        public IList<Book> Books { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace EtLiberLibrarium.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/AccountController.cs
using EtLiberLibrarium.Data;
using EtLiberLibrarium.Data.Models;
using EtLiberLibrarium.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EtLiberLibrarium.Controllers
{
    public class AccountController : Controller
    {
        private BooksContext _db;

        public AccountController(BooksContext injectedContext)
        {
            _db = injectedContext;
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }
    }
}

Controllers/DatabaseController.cs
using EtLiberLibrarium.Data;
using EtLiberLibrarium.Data.Models;
using EtLiberLibrarium.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace EtLiberLibrarium.Controllers
{
    public class DatabaseController : Controller
    {
        private readonly ILogger<DatabaseController> _logger;
        private BooksContext _db;

        public DatabaseController(ILogger<DatabaseController> logger, BooksContext injectedContext)
        {
            _logger = logger;
            _db = injectedContext;
        }

        public async Task<IActionResult> Index()
        {
            var model = new DatabaseIndexViewModel()
            {
                Books = await _db.Books.ToListAsync()
            };
            return View(model);
        }

        public IActionResult Search()
        {
            var model = new DatabaseIndexViewModel()
            {
                Books = _db.Books.ToList()
            };
            return View(model);
        }

        public IActionResult Upload()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> ViewBook([FromQuery]int itemid)
        {
            var book = await _db.Books.FindAsync(itemid);
            if (book == null)
                book = new Book();
            var model = new DatabaseBookViewModel()
            {
                Book = book
            };
            return View(model);
        }
    }
}

Controllers/HomeController.cs
using EtLiberLibrarium.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace EtLiberLibrarium.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Database/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Books";
    Layout = "_DatabaseLayout";
}
<h3>
    Database View
</h3>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">ISBN</th>
            <th scope="col">Hash</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model.Books){
        <tr>
            <td><a class="text-body" asp-controller="Database" asp-action="ViewBook" asp-route-itemid="@item.BookId">@item.Title</a></td>
            <td tabindex="-1">@item.ISBN</td>
            <td tabindex="-1">@item.Hash</td>
        </tr>
        }
    </tbody>
</table>

Views/Database/Search.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_DatabaseLayout";
}

<h3>
    Search
</h3>

<form>
    <div class="container">
        <div class="row">
            <div class="col">
                <label>Book Title</label>
                <input type="text"/>
            </div>
            <div class="col">
                <label>ISBN</label>
                <input type="text"/>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <input type="submit"/>
            </div>
            <div class="col">
            
            </div>
        </div>
        <div class="row">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">ISBN</th>
                        <th scope="col">Hash</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach(var item in Model.Books){
                    <tr>
                        <td>@item.Title</td>
                        <td>@item.ISBN</td>
                        <td>@item.Hash</td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</form>

Views/Database/Upload.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_DatabaseLayout";
}

Views/Database/ViewBook.cshtml
@{
    Layout = "_DatabaseLayout";
}

<div class="container">
	<div class="col">
		<div class="row">
			<span>Title: </span>
			<br />
			<span>@Model.Book.Title</span>
		</div> 
	</div>
	<div class="col">
		<div class="row">
		
		</div> 
	</div>
</div>

Views/Database/_DatabaseLayout.cshtml
@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="container">
            <div class="row">
                <div class="col-2">
                    <div class="row">
                        <a class="nav-link btn-primary btn-block rounded-pill mb-1" 
                            asp-area="" asp-controller="Database" asp-action="Index">Books</a>
                    </div>
                    <div class="row">
                        <a class="nav-link btn-primary btn-block rounded-pill mb-1" 
                            asp-area="" asp-controller="Database" asp-action="Search">Search</a>
                    </div>
                    <div class="row">
                        <a class="nav-link btn-primary btn-block rounded-pill mb-1" 
                            asp-area="" asp-controller="Database" asp-action="Upload">Upload</a>
                    </div>
                </div>
                <div class="col-10 container">
                    @RenderBody()
                </div>
            </div>
        </div>
</body>
</html>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EtLiberLibrarium</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EtLiberLibrarium</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Database" asp-action="Index">Database</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - EtLiberLibrarium - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>